### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by StarsDown64** [STARS-Design-Track-2023/MatrixMonSTARS#8]

**Comment by vclagudu** [comment]
Documentation added

**Comment by StarsDown64** [comment]
The pic is super blurry. Maybe a better pic or listing it in text would be good. Up to you.

**Comment by StarsDown64** [comment]
Bigger problem is idk what's I/O. I could guess but I don't want to mess up your stuff. Also could include the preferred GPIO mapping.

**Comment by vclagudu** [comment]
Fixed
